
services:
  grpc_server:
    build:
      context: .
      dockerfile: Dockerfile.grpc
    container_name: grpc-server
    volumes:
      - .:/grpc
    ports:
      - "50051:50051"

  client:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: grpc-client
    volumes:
      - .:/app
    ports:
      - "8081:8081"
    depends_on:
      - grpc_server