version: '3.8'

services:
  grpc_server:
    build:
      context: .
      dockerfile: Dockerfile.grpc
    container_name: grpc-server
    volumes:
      - .:/grpc
    ports:
      - "50051:50051"

  http_server:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: http-server
    volumes:
      - .:/app
    ports:
      - "8081:8081"
    depends_on:
      - grpc_server