FROM python:3.7-alpine

WORKDIR /app

COPY ./grpc_server.py /app
COPY ./meterusage_pb2.py /app
COPY ./meterusage_pb2_grpc.py /app

COPY ./requirements.txt /app/requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run meterusage_server.py when the container launches
CMD ["python", "server.py"]
